package paquete;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dfcm9
 */
public class Admin extends javax.swing.JFrame {
    
    //ArrayList<Jugador> jugind = new ArrayList();
    ArrayList<Equipo> equipos = new ArrayList();
    ArrayList<Estadio> estadios = new ArrayList();
    ArrayList<Jugador> jugadores = new ArrayList();
    

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        jp_addjug.setVisible(false);
        jp_addequip.setVisible(false);
        jp_addestadio.setVisible(false);
        jp_modjugador.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_main = new javax.swing.JPanel();
        jb_modificarequipo = new javax.swing.JButton();
        jb_simular = new javax.swing.JButton();
        jb_elimjugador = new javax.swing.JButton();
        jb_modificarestadio = new javax.swing.JButton();
        jb_modificarjugador = new javax.swing.JButton();
        jb_agregarestadio = new javax.swing.JButton();
        jb_agregarequipo = new javax.swing.JButton();
        jb_addjugador = new javax.swing.JButton();
        jb_elimequipo = new javax.swing.JButton();
        jb_elimestadio = new javax.swing.JButton();
        jb_listar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jp_addestadio = new javax.swing.JPanel();
        jl_estadiociudad = new javax.swing.JLabel();
        jl_titleaddestadio = new javax.swing.JLabel();
        jl_addestadioname = new javax.swing.JLabel();
        tf_estadionombre = new javax.swing.JTextField();
        tf_estadiociudad = new javax.swing.JTextField();
        jb_addestadio = new javax.swing.JButton();
        jl_estadiocap = new javax.swing.JLabel();
        jl_estadioequipo = new javax.swing.JLabel();
        tf_estadiocap = new javax.swing.JTextField();
        cb_estadioequipo = new javax.swing.JComboBox<>();
        jp_addjug = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jl_tipo = new javax.swing.JLabel();
        tf_nomjug = new javax.swing.JTextField();
        jl_edad = new javax.swing.JLabel();
        jl_nacionalidad = new javax.swing.JLabel();
        tf_nacionjug = new javax.swing.JTextField();
        ff_edadjug = new javax.swing.JFormattedTextField();
        jl_piehabil = new javax.swing.JLabel();
        tf_piejug = new javax.swing.JTextField();
        jb_agregar = new javax.swing.JButton();
        jl_nombre1 = new javax.swing.JLabel();
        cb_tipojug = new javax.swing.JComboBox<>();
        jl_piehabil1 = new javax.swing.JLabel();
        cb_equipos = new javax.swing.JComboBox<>();
        jp_modjugador = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jl_tipo1 = new javax.swing.JLabel();
        tf_nomjug1 = new javax.swing.JTextField();
        jl_edad1 = new javax.swing.JLabel();
        jl_nacionalidad1 = new javax.swing.JLabel();
        tf_nacionjug1 = new javax.swing.JTextField();
        ff_edadjug1 = new javax.swing.JFormattedTextField();
        jl_piehabil2 = new javax.swing.JLabel();
        tf_piejug1 = new javax.swing.JTextField();
        jb_ModJugador = new javax.swing.JButton();
        jl_nombre2 = new javax.swing.JLabel();
        cb_jugadores = new javax.swing.JComboBox<>();
        jl_piehabil3 = new javax.swing.JLabel();
        cb_equipos1 = new javax.swing.JComboBox<>();
        jp_modEquipo = new javax.swing.JPanel();
        jl_title5 = new javax.swing.JLabel();
        jl_title6 = new javax.swing.JLabel();
        jl_title7 = new javax.swing.JLabel();
        tf_equiponombre1 = new javax.swing.JTextField();
        tf_equipopais1 = new javax.swing.JTextField();
        jb_addequipo1 = new javax.swing.JButton();
        jp_addequip = new javax.swing.JPanel();
        jl_title2 = new javax.swing.JLabel();
        jl_title3 = new javax.swing.JLabel();
        jl_title4 = new javax.swing.JLabel();
        tf_equiponombre = new javax.swing.JTextField();
        tf_equipopais = new javax.swing.JTextField();
        jb_addequipo = new javax.swing.JButton();
        jl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_main.setBackground(new java.awt.Color(255, 255, 255));
        jp_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_modificarequipo.setBackground(new java.awt.Color(0, 51, 51));
        jb_modificarequipo.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_modificarequipo.setForeground(new java.awt.Color(255, 255, 255));
        jb_modificarequipo.setText("Modificar Equipo");
        jp_main.add(jb_modificarequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, 30));

        jb_simular.setBackground(new java.awt.Color(0, 51, 51));
        jb_simular.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_simular.setForeground(new java.awt.Color(255, 255, 255));
        jb_simular.setText("Simulacion");
        jp_main.add(jb_simular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 140, 30));

        jb_elimjugador.setBackground(new java.awt.Color(0, 51, 51));
        jb_elimjugador.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_elimjugador.setForeground(new java.awt.Color(255, 255, 255));
        jb_elimjugador.setText("Eliminar Jugador");
        jp_main.add(jb_elimjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, 30));

        jb_modificarestadio.setBackground(new java.awt.Color(0, 51, 51));
        jb_modificarestadio.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_modificarestadio.setForeground(new java.awt.Color(255, 255, 255));
        jb_modificarestadio.setText("Modificar Estadio");
        jp_main.add(jb_modificarestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 30));

        jb_modificarjugador.setBackground(new java.awt.Color(0, 51, 51));
        jb_modificarjugador.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_modificarjugador.setForeground(new java.awt.Color(255, 255, 255));
        jb_modificarjugador.setText("Modificar Jugador");
        jb_modificarjugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarjugadorMouseClicked(evt);
            }
        });
        jb_modificarjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarjugadorActionPerformed(evt);
            }
        });
        jp_main.add(jb_modificarjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 30));

        jb_agregarestadio.setBackground(new java.awt.Color(0, 51, 51));
        jb_agregarestadio.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_agregarestadio.setForeground(new java.awt.Color(255, 255, 255));
        jb_agregarestadio.setText("Agregar Estadio");
        jb_agregarestadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarestadioMouseClicked(evt);
            }
        });
        jp_main.add(jb_agregarestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 30));

        jb_agregarequipo.setBackground(new java.awt.Color(0, 51, 51));
        jb_agregarequipo.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_agregarequipo.setForeground(new java.awt.Color(255, 255, 255));
        jb_agregarequipo.setText("Agregar Equipo");
        jb_agregarequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarequipoMouseClicked(evt);
            }
        });
        jp_main.add(jb_agregarequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 30));

        jb_addjugador.setBackground(new java.awt.Color(0, 51, 51));
        jb_addjugador.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_addjugador.setForeground(new java.awt.Color(255, 255, 255));
        jb_addjugador.setText("Agregar Jugador");
        jb_addjugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addjugadorMouseClicked(evt);
            }
        });
        jb_addjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_addjugadorActionPerformed(evt);
            }
        });
        jp_main.add(jb_addjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 30));

        jb_elimequipo.setBackground(new java.awt.Color(0, 51, 51));
        jb_elimequipo.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_elimequipo.setForeground(new java.awt.Color(255, 255, 255));
        jb_elimequipo.setText("Eliminar Equipo");
        jp_main.add(jb_elimequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 140, 30));

        jb_elimestadio.setBackground(new java.awt.Color(0, 51, 51));
        jb_elimestadio.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_elimestadio.setForeground(new java.awt.Color(255, 255, 255));
        jb_elimestadio.setText("Eliminar Estadio");
        jb_elimestadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_elimestadioActionPerformed(evt);
            }
        });
        jp_main.add(jb_elimestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 30));

        jb_listar.setBackground(new java.awt.Color(0, 51, 51));
        jb_listar.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jb_listar.setForeground(new java.awt.Color(255, 255, 255));
        jb_listar.setText("Listar");
        jp_main.add(jb_listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 140, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FIFA MENU");
        jp_main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 30));

        jp_addestadio.setBackground(new java.awt.Color(153, 153, 255));

        jl_estadiociudad.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_estadiociudad.setForeground(new java.awt.Color(255, 255, 255));
        jl_estadiociudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_estadiociudad.setText("CIUDAD");

        jl_titleaddestadio.setBackground(new java.awt.Color(0, 153, 255));
        jl_titleaddestadio.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_titleaddestadio.setForeground(new java.awt.Color(255, 255, 255));
        jl_titleaddestadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titleaddestadio.setText("AGREGAR ESTADIO");

        jl_addestadioname.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_addestadioname.setForeground(new java.awt.Color(255, 255, 255));
        jl_addestadioname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_addestadioname.setText("NOMBRE");

        tf_estadiociudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_estadiociudadActionPerformed(evt);
            }
        });

        jb_addestadio.setBackground(new java.awt.Color(153, 0, 153));
        jb_addestadio.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jb_addestadio.setForeground(new java.awt.Color(255, 255, 255));
        jb_addestadio.setText("AGREGAR");
        jb_addestadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addestadioMouseClicked(evt);
            }
        });

        jl_estadiocap.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_estadiocap.setForeground(new java.awt.Color(255, 255, 255));
        jl_estadiocap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_estadiocap.setText("CAPACIDAD");

        jl_estadioequipo.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_estadioequipo.setForeground(new java.awt.Color(255, 255, 255));
        jl_estadioequipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_estadioequipo.setText("EQUIPO");

        javax.swing.GroupLayout jp_addestadioLayout = new javax.swing.GroupLayout(jp_addestadio);
        jp_addestadio.setLayout(jp_addestadioLayout);
        jp_addestadioLayout.setHorizontalGroup(
            jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addestadioLayout.createSequentialGroup()
                .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_addestadioLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_addestadioLayout.createSequentialGroup()
                                .addComponent(jl_addestadioname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(tf_estadionombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_addestadioLayout.createSequentialGroup()
                                .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jp_addestadioLayout.createSequentialGroup()
                                        .addComponent(jl_estadioequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_addestadioLayout.createSequentialGroup()
                                        .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jl_estadiociudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jl_estadiocap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_estadiociudad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_estadiocap, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_estadioequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jp_addestadioLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jl_titleaddestadio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_addestadioLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jb_addestadio, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jp_addestadioLayout.setVerticalGroup(
            jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addestadioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jl_titleaddestadio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_estadionombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_addestadioname, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_estadiociudad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_estadiociudad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_estadiocap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_estadiocap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_addestadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_estadioequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_estadioequipo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jb_addestadio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jp_main.add(jp_addestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 10, 690, 510));

        jp_addjug.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Jugador");

        jl_tipo.setBackground(new java.awt.Color(0, 0, 0));
        jl_tipo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_tipo.setForeground(new java.awt.Color(0, 0, 0));
        jl_tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_tipo.setText("Tipo de Jugador");

        jl_edad.setBackground(new java.awt.Color(0, 0, 0));
        jl_edad.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_edad.setForeground(new java.awt.Color(0, 0, 0));
        jl_edad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_edad.setText("Edad");

        jl_nacionalidad.setBackground(new java.awt.Color(0, 0, 0));
        jl_nacionalidad.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_nacionalidad.setForeground(new java.awt.Color(0, 0, 0));
        jl_nacionalidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_nacionalidad.setText("Nacionalidad");

        ff_edadjug.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jl_piehabil.setBackground(new java.awt.Color(0, 0, 0));
        jl_piehabil.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_piehabil.setForeground(new java.awt.Color(0, 0, 0));
        jl_piehabil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_piehabil.setText("Pie Habil");

        jb_agregar.setBackground(new java.awt.Color(0, 153, 0));
        jb_agregar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jb_agregar.setForeground(new java.awt.Color(0, 0, 0));
        jb_agregar.setText("AGREGAR");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        jl_nombre1.setBackground(new java.awt.Color(0, 0, 0));
        jl_nombre1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_nombre1.setForeground(new java.awt.Color(0, 0, 0));
        jl_nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_nombre1.setText("Nombre");

        cb_tipojug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero" }));

        jl_piehabil1.setBackground(new java.awt.Color(0, 0, 0));
        jl_piehabil1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_piehabil1.setForeground(new java.awt.Color(0, 0, 0));
        jl_piehabil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_piehabil1.setText("Equipo");

        javax.swing.GroupLayout jp_addjugLayout = new javax.swing.GroupLayout(jp_addjug);
        jp_addjug.setLayout(jp_addjugLayout);
        jp_addjugLayout.setHorizontalGroup(
            jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_addjugLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_addjugLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_addjugLayout.createSequentialGroup()
                        .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ff_edadjug)
                                .addComponent(tf_nomjug, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_nacionjug, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_addjugLayout.createSequentialGroup()
                        .addComponent(jl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_tipojug, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_addjugLayout.createSequentialGroup()
                        .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_piehabil, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_piehabil1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_piejug)
                            .addComponent(cb_equipos, 0, 235, Short.MAX_VALUE))))
                .addGap(138, 138, 138))
        );
        jp_addjugLayout.setVerticalGroup(
            jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addjugLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cb_tipojug))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nomjug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nombre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ff_edadjug, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nacionjug, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_piehabil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_piejug, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_addjugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_piehabil1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cb_equipos))
                .addGap(38, 38, 38)
                .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jp_main.add(jp_addjug, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 690, 520));

        jp_modjugador.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Modificar Jugador");

        jl_tipo1.setBackground(new java.awt.Color(0, 0, 0));
        jl_tipo1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_tipo1.setForeground(new java.awt.Color(0, 0, 0));
        jl_tipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_tipo1.setText("Jugador a Modificar");

        jl_edad1.setBackground(new java.awt.Color(0, 0, 0));
        jl_edad1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_edad1.setForeground(new java.awt.Color(0, 0, 0));
        jl_edad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_edad1.setText("Edad");

        jl_nacionalidad1.setBackground(new java.awt.Color(0, 0, 0));
        jl_nacionalidad1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_nacionalidad1.setForeground(new java.awt.Color(0, 0, 0));
        jl_nacionalidad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_nacionalidad1.setText("Nacionalidad");

        ff_edadjug1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jl_piehabil2.setBackground(new java.awt.Color(0, 0, 0));
        jl_piehabil2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_piehabil2.setForeground(new java.awt.Color(0, 0, 0));
        jl_piehabil2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_piehabil2.setText("Pie Habil");

        jb_ModJugador.setBackground(new java.awt.Color(0, 153, 0));
        jb_ModJugador.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jb_ModJugador.setForeground(new java.awt.Color(0, 0, 0));
        jb_ModJugador.setText("MODIFICAR");
        jb_ModJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ModJugadorMouseClicked(evt);
            }
        });
        jb_ModJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModJugadorActionPerformed(evt);
            }
        });

        jl_nombre2.setBackground(new java.awt.Color(0, 0, 0));
        jl_nombre2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_nombre2.setForeground(new java.awt.Color(0, 0, 0));
        jl_nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_nombre2.setText("Nombre");

        jl_piehabil3.setBackground(new java.awt.Color(0, 0, 0));
        jl_piehabil3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_piehabil3.setForeground(new java.awt.Color(0, 0, 0));
        jl_piehabil3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_piehabil3.setText("Equipo");

        javax.swing.GroupLayout jp_modjugadorLayout = new javax.swing.GroupLayout(jp_modjugador);
        jp_modjugador.setLayout(jp_modjugadorLayout);
        jp_modjugadorLayout.setHorizontalGroup(
            jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_modjugadorLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jb_ModJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_modjugadorLayout.createSequentialGroup()
                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_modjugadorLayout.createSequentialGroup()
                        .addContainerGap(142, Short.MAX_VALUE)
                        .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_modjugadorLayout.createSequentialGroup()
                                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_nacionalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ff_edadjug1)
                                        .addComponent(tf_nomjug1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_nacionjug1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_modjugadorLayout.createSequentialGroup()
                                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_piehabil2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_piehabil3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_piejug1)
                                    .addComponent(cb_equipos1, 0, 235, Short.MAX_VALUE)))))
                    .addGroup(jp_modjugadorLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jl_tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_jugadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(138, 138, 138))
        );
        jp_modjugadorLayout.setVerticalGroup(
            jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modjugadorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_tipo1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cb_jugadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nomjug1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nombre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ff_edadjug1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nacionjug1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nacionalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_piehabil2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_piejug1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_modjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_piehabil3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cb_equipos1))
                .addGap(38, 38, 38)
                .addComponent(jb_ModJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jp_main.add(jp_modjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 690, 520));

        jp_modEquipo.setBackground(new java.awt.Color(0, 102, 51));

        jl_title5.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_title5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_title5.setText("PAIS");

        jl_title6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_title6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_title6.setText("AGREGAR EQUIPO");

        jl_title7.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_title7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_title7.setText("NOMBRE");

        tf_equipopais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_equipopais1ActionPerformed(evt);
            }
        });

        jb_addequipo1.setBackground(new java.awt.Color(0, 153, 255));
        jb_addequipo1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jb_addequipo1.setForeground(new java.awt.Color(255, 255, 255));
        jb_addequipo1.setText("AGREGAR");
        jb_addequipo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addequipo1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_modEquipoLayout = new javax.swing.GroupLayout(jp_modEquipo);
        jp_modEquipo.setLayout(jp_modEquipoLayout);
        jp_modEquipoLayout.setHorizontalGroup(
            jp_modEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modEquipoLayout.createSequentialGroup()
                .addGroup(jp_modEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_modEquipoLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jp_modEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_modEquipoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jl_title7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_equiponombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_modEquipoLayout.createSequentialGroup()
                                .addComponent(jl_title5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_equipopais1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_modEquipoLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jb_addequipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_modEquipoLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jl_title6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jp_modEquipoLayout.setVerticalGroup(
            jp_modEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modEquipoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jl_title6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jp_modEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_equiponombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_title7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp_modEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_title5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_equipopais1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(jb_addequipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jp_main.add(jp_modEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 10, 680, 510));

        jp_addequip.setBackground(new java.awt.Color(0, 102, 51));

        jl_title2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_title2.setText("PAIS");

        jl_title3.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_title3.setText("MODIFICAR EQUIPO");

        jl_title4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jl_title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_title4.setText("NOMBRE");

        tf_equipopais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_equipopaisActionPerformed(evt);
            }
        });

        jb_addequipo.setBackground(new java.awt.Color(0, 153, 255));
        jb_addequipo.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jb_addequipo.setForeground(new java.awt.Color(255, 255, 255));
        jb_addequipo.setText("AGREGAR");
        jb_addequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addequipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_addequipLayout = new javax.swing.GroupLayout(jp_addequip);
        jp_addequip.setLayout(jp_addequipLayout);
        jp_addequipLayout.setHorizontalGroup(
            jp_addequipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addequipLayout.createSequentialGroup()
                .addGroup(jp_addequipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_addequipLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jp_addequipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_addequipLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jl_title4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_equiponombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_addequipLayout.createSequentialGroup()
                                .addComponent(jl_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_equipopais, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_addequipLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jb_addequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_addequipLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jl_title3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jp_addequipLayout.setVerticalGroup(
            jp_addequipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addequipLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jl_title3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jp_addequipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_equiponombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_title4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp_addequipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_equipopais, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(jb_addequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jp_main.add(jp_addequip, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 10, 680, 510));

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/fut.jpg"))); // NOI18N
        jl_fondo.setText("jLabel1");
        jp_main.add(jl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 1130, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_addjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_addjugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_addjugadorActionPerformed

    private void jb_modificarjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarjugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_modificarjugadorActionPerformed

    private void jb_elimestadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_elimestadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_elimestadioActionPerformed

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        
        
        if (cb_tipojug.getSelectedIndex()==0){
        Portero x = new Portero();
        x.setNombre(tf_nomjug.getText());
        x.setEdad(Integer.parseInt(ff_edadjug.getText()));
        x.setNacionalidad(tf_nacionjug.getText());
        x.setPieh(tf_piejug.getText());
        equipos.get(cb_equipos.getSelectedIndex()).getPlantilla().add(x);
        jugadores.add(x);
        JOptionPane.showMessageDialog(this, "Jugador agregado exitosamente!");
            
            
        }
        else if (cb_tipojug.getSelectedIndex()==1){
            Defensa x = new Defensa();
            x.setNombre(tf_nomjug.getText());
            x.setEdad(Integer.parseInt(ff_edadjug.getText()));
            x.setNacionalidad(tf_nacionjug.getText());
            x.setPieh(tf_piejug.getText());
            equipos.get(cb_equipos.getSelectedIndex()).getPlantilla().add(x);
            JOptionPane.showMessageDialog(this, "Jugador agregado exitosamente!");
            jugadores.add(x);
            
        }
        else if (cb_tipojug.getSelectedIndex()==2){
            Mediocampista x = new Mediocampista();
            x.setNombre(tf_nomjug.getText());
            x.setEdad(Integer.parseInt(ff_edadjug.getText()));
            x.setNacionalidad(tf_nacionjug.getText());
            x.setPieh(tf_piejug.getText());
            equipos.get(cb_equipos.getSelectedIndex()).getPlantilla().add(x);
            JOptionPane.showMessageDialog(this, "Jugador agregado exitosamente!");
            jugadores.add(x);
            
        }
        else if (cb_tipojug.getSelectedIndex()==3){
            Delantero x = new Delantero();
            x.setNombre(tf_nomjug.getText());
            x.setEdad(Integer.parseInt(ff_edadjug.getText()));
            x.setNacionalidad(tf_nacionjug.getText());
            x.setPieh(tf_piejug.getText());
            equipos.get(cb_equipos.getSelectedIndex()).getPlantilla().add(x);
            JOptionPane.showMessageDialog(this, "Jugador agregado exitosamente!");
            jugadores.add(x);
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jb_addjugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addjugadorMouseClicked
        if (equipos.isEmpty()){
            JOptionPane.showMessageDialog(null, "No puede agregar jugadores si no ha agregado un equipo");
            
        }
        else{
            DefaultComboBoxModel modelo = ((DefaultComboBoxModel)cb_equipos.getModel());
            for (Equipo equipo : equipos) {
                modelo.addElement(equipo);

            }
            cb_equipos.setModel(modelo);
            jp_addjug.setVisible(true);
            jp_addequip.setVisible(false);
            jp_addestadio.setVisible(false);
            jp_modjugador.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jb_addjugadorMouseClicked

    private void tf_equipopaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_equipopaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_equipopaisActionPerformed

    private void jb_addequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addequipoMouseClicked
        Equipo y = new Equipo();
        y.setNombre(tf_equiponombre.getText());
        y.setPais(tf_equipopais.getText());
        equipos.add(y);
        JOptionPane.showMessageDialog(this, "Equipo agregado exitosamente!");
    }//GEN-LAST:event_jb_addequipoMouseClicked

    private void jb_agregarequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarequipoMouseClicked
        jp_addequip.setVisible(true);
        jp_addjug.setVisible(false);
        jp_addestadio.setVisible(false);
        jp_modjugador.setVisible(false);
    }//GEN-LAST:event_jb_agregarequipoMouseClicked

    private void tf_estadiociudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_estadiociudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_estadiociudadActionPerformed

    private void jb_addestadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addestadioMouseClicked
        Estadio z = new Estadio();
        z.setNombre(tf_estadionombre.getText());
        z.setCiudad(tf_estadiociudad.getText());
        z.setCapacidad(Integer.parseInt(tf_estadiocap.getText()));
        z.setEquipo(equipos.get(cb_estadioequipo.getSelectedIndex()));
        estadios.add(z);
        JOptionPane.showMessageDialog(this,"El estadio ha sido agregado exitosamente!");
    
    }//GEN-LAST:event_jb_addestadioMouseClicked

    private void jb_agregarestadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarestadioMouseClicked
        
        if (equipos.isEmpty()){
            JOptionPane.showMessageDialog(null, "No puede agregar un estadio si no ha agregado un equipo.");
            
        }
        else{
            jp_addequip.setVisible(false);
            jp_addjug.setVisible(false);
            jp_addestadio.setVisible(true);
            jp_modjugador.setVisible(false);
            DefaultComboBoxModel modelo = ((DefaultComboBoxModel)cb_estadioequipo.getModel());
            for (Equipo equipo : equipos) {
                modelo.addElement(equipo);
            
            }
            cb_estadioequipo.setModel(modelo);
        }
        
    }//GEN-LAST:event_jb_agregarestadioMouseClicked

    private void jb_ModJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ModJugadorMouseClicked
        Jugador x = jugadores.get(cb_jugadores.getSelectedIndex());
        Equipo a = jugadores.get(cb_jugadores.getSelectedIndex()).getEquipo();
        for (Equipo equipo : equipos) {
            if (equipos.contains(a)){
                a.getPlantilla().remove(cb_jugadores.getSelectedIndex());
            }
        }
        x.setNombre(tf_nomjug1.getText());
        x.setNacionalidad(tf_nacionjug1.getText());
        x.setEdad(Integer.parseInt(ff_edadjug1.getText()));
        x.setPieh(tf_piejug1.getText());
        x.setEquipo((Equipo) cb_equipos1.getSelectedItem());
        jugadores.remove(cb_jugadores.getSelectedIndex());
        equipos.get(cb_equipos1.getSelectedIndex()).getPlantilla().add(x);
        jugadores.add(x);
        JOptionPane.showMessageDialog(this,"Jugador Modificado Exitosamente!");
        
        
        
    }//GEN-LAST:event_jb_ModJugadorMouseClicked

    private void jb_ModJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ModJugadorActionPerformed

    private void jb_modificarjugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarjugadorMouseClicked
        jp_modjugador.setVisible(true);
        jp_addjug.setVisible(false);
        jp_addequip.setVisible(false);
        jp_addestadio.setVisible(false);
        DefaultComboBoxModel modelo = ((DefaultComboBoxModel)cb_jugadores.getModel());
            for (Jugador jug : jugadores) {
                modelo.addElement(jug);

            }
            cb_jugadores.setModel(modelo);
        DefaultComboBoxModel modelo2 = ((DefaultComboBoxModel)cb_equipos1.getModel());
            for (Equipo equipo : equipos) {
                modelo2.addElement(equipo);

            }
            cb_equipos1.setModel(modelo2);
    }//GEN-LAST:event_jb_modificarjugadorMouseClicked

    private void tf_equipopais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_equipopais1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_equipopais1ActionPerformed

    private void jb_addequipo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addequipo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_addequipo1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_equipos;
    private javax.swing.JComboBox<String> cb_equipos1;
    private javax.swing.JComboBox<String> cb_estadioequipo;
    private javax.swing.JComboBox<String> cb_jugadores;
    private javax.swing.JComboBox<String> cb_tipojug;
    private javax.swing.JFormattedTextField ff_edadjug;
    private javax.swing.JFormattedTextField ff_edadjug1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_ModJugador;
    private javax.swing.JButton jb_addequipo;
    private javax.swing.JButton jb_addequipo1;
    private javax.swing.JButton jb_addestadio;
    private javax.swing.JButton jb_addjugador;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_agregarequipo;
    private javax.swing.JButton jb_agregarestadio;
    private javax.swing.JButton jb_elimequipo;
    private javax.swing.JButton jb_elimestadio;
    private javax.swing.JButton jb_elimjugador;
    private javax.swing.JButton jb_listar;
    private javax.swing.JButton jb_modificarequipo;
    private javax.swing.JButton jb_modificarestadio;
    private javax.swing.JButton jb_modificarjugador;
    private javax.swing.JButton jb_simular;
    private javax.swing.JLabel jl_addestadioname;
    private javax.swing.JLabel jl_edad;
    private javax.swing.JLabel jl_edad1;
    private javax.swing.JLabel jl_estadiocap;
    private javax.swing.JLabel jl_estadiociudad;
    private javax.swing.JLabel jl_estadioequipo;
    private javax.swing.JLabel jl_fondo;
    private javax.swing.JLabel jl_nacionalidad;
    private javax.swing.JLabel jl_nacionalidad1;
    private javax.swing.JLabel jl_nombre1;
    private javax.swing.JLabel jl_nombre2;
    private javax.swing.JLabel jl_piehabil;
    private javax.swing.JLabel jl_piehabil1;
    private javax.swing.JLabel jl_piehabil2;
    private javax.swing.JLabel jl_piehabil3;
    private javax.swing.JLabel jl_tipo;
    private javax.swing.JLabel jl_tipo1;
    private javax.swing.JLabel jl_title2;
    private javax.swing.JLabel jl_title3;
    private javax.swing.JLabel jl_title4;
    private javax.swing.JLabel jl_title5;
    private javax.swing.JLabel jl_title6;
    private javax.swing.JLabel jl_title7;
    private javax.swing.JLabel jl_titleaddestadio;
    private javax.swing.JPanel jp_addequip;
    private javax.swing.JPanel jp_addestadio;
    private javax.swing.JPanel jp_addjug;
    private javax.swing.JPanel jp_main;
    private javax.swing.JPanel jp_modEquipo;
    private javax.swing.JPanel jp_modjugador;
    private javax.swing.JTextField tf_equiponombre;
    private javax.swing.JTextField tf_equiponombre1;
    private javax.swing.JTextField tf_equipopais;
    private javax.swing.JTextField tf_equipopais1;
    private javax.swing.JTextField tf_estadiocap;
    private javax.swing.JTextField tf_estadiociudad;
    private javax.swing.JTextField tf_estadionombre;
    private javax.swing.JTextField tf_nacionjug;
    private javax.swing.JTextField tf_nacionjug1;
    private javax.swing.JTextField tf_nomjug;
    private javax.swing.JTextField tf_nomjug1;
    private javax.swing.JTextField tf_piejug;
    private javax.swing.JTextField tf_piejug1;
    // End of variables declaration//GEN-END:variables
}
